CREATE DATABASE IF NOT EXISTS mydb;

USE mydb;

CREATE USER IF NOT EXISTS 'myuser'@'%' IDENTIFIED BY 'mypassword';

GRANT ALL PRIVILEGES ON mydb.* TO 'myuser'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;